/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lapr.project.controller.RemoverCandidaturaController;
import lapr.project.model.Candidatura;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Utilizador;

/**
 *
 * @author Joao Sousa
 */
public class JanelaRemoverCandidatura extends javax.swing.JFrame {

    private final RemoverCandidaturaController m_rcController;
    private final CentroExposicoes centro;
    private final Utilizador representante;
    private DefaultListModel dlm_listaCandidaturas;
    
    /**
     * Creates new form JanelaRemoverCandidatura
     * @param c
     * @param r
     */
    public JanelaRemoverCandidatura(CentroExposicoes c, Utilizador r) {
        this.centro = c;
        m_rcController = new RemoverCandidaturaController(this.centro);
        this.representante = r;
        this.dlm_listaCandidaturas=new DefaultListModel();
        initComponents();
        
        loadList();
        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    public void loadList(){
        dlm_listaCandidaturas.clear();
        for(Candidatura c : this.m_rcController.getListCandidaturasPorRepres(this.representante)){
            dlm_listaCandidaturas.addElement(c);
        }
        listaCandidaturas.setModel(dlm_listaCandidaturas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaCandidaturas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        removerButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listaCandidaturas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Candidaturas Submetidas pelo utilizador:");

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelarButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        JanelaPrincipal j = new JanelaPrincipal(this.centro, this.representante);
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        try{
            if(listaCandidaturas.getSelectedValue() == null){
                throw new IllegalArgumentException("Selecione uma candidatura");
            }
            this.m_rcController.getExposicaoPorCandidatura(listaCandidaturas.getSelectedValue());
            JOptionPane.showMessageDialog(this,"Removeu a candidatura com sucesso.");
            JanelaPrincipal j = new JanelaPrincipal(centro, representante);
            dispose();
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_removerButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Candidatura> listaCandidaturas;
    private javax.swing.JButton removerButton;
    // End of variables declaration//GEN-END:variables
}
